version: 2.6.1-{build}

image: Visual Studio 2017

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore

build_script:
  - dotnet build src\LaunchDarkly.CommonSdk\LaunchDarkly.CommonSdk.csproj

after_build:
  - dotnet pack src\LaunchDarkly.CommonSdk\LaunchDarkly.CommonSdk.csproj

test_script:
  - dotnet test test\LaunchDarkly.CommonSdk.Tests\LaunchDarkly.CommonSdk.Tests.csproj

artifacts:
  - path: 'src\LaunchDarkly.CommonSdk\bin\**\*.nupkg'
    name: Nuget
